config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/',include('pybo.urls')),
]

pybo/urls.py
from django.urls import path

from . import views
# 여기서 .의 의미는?
app_name = 'pybo'
#네임스페이스.-> 해주고 html에 네잇므페이스 pybo를 적어줘야함
urlpatterns = [
    path('',views.index, name='index'),
    # views.py의 index를 index로 호출가능하게 해버림
    path('<int:question_id>/', views.detail,name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),

    # views.py의 detail을 detail이라는 것만으로 호출가능하게 바꿈.
    #매핑을 추가해서 id를 잘 잡아서 띄워줄 ㄹ것이다! by views.detail(views.py에 detail 만들어줘야댐)
]

pybo/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    #제목 최대 200개의 charField(글자갯수)
    content = models.TextField()
    # 질문내용은 텍스트필드 빈칸
    create_date = models.DateTimeField()
    # 질문 날짜는 시간필드
    def __str__(self):
        return self.subject
    #https://jamanbbo.tistory.com/11 str메서드
class Answer(models.Model):

    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    # 포린키 안에 짝 지어져 있는 이유와. on delete 뜻?
    # Question을 속성으로 가져가기 위해 앞에 두고,
    # 뒤의 뜻은 Question 속성이 사라진다면 답변도 삭제된다.
    content = models.TextField()
    create_date = models.DateTimeField()

    

pybo/forms.py
from django import forms
from pybo.models import Question,Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }        

pybo/views.py
from django.shortcuts import render
from .models import Question
from django.shortcuts import get_object_or_404, redirect
from django.utils import timezone
from .forms import QuestionForm
from .forms import AnswerForm
from django.http import HttpResponseNotAllowed
#R1위한 모듈
def index(request):
    question_list = Question.objects.order_by('-create_date')
    # 질문 목록 데이터 얻기 생성일자순으로
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)
    #렌더함수에서사용한 html 템플릿 파일 작성하기!
    
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)
    # R1.id에 없는 데이터를 요청하는 경우 404 출력하기위해 약간의 수정 ㄱ
    # R1이전 : question = Question.objects.get(id=question_id)
# Create your views here.

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
        else:
            return HttpResponseNotAllowed('Only POST is possible.')
        context = {'question': question, 'form': form}
        return render(request, 'pybo/question_detail.html', context)

# 상세호출 위한 answer ceate 함수를 만들어주어서 이것을 hrl매핑 등록하서  질문상세까지연동
# 그렇게 해서 질문->바로 답변 할수있게.

def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

#question_create 버튼 함수를 만들어서 버튼이 작동하도록 해주 었따.ㄴ
# 링크를통해 페이지를 요청하는 시에는 자동으로 Get.
# 그래서 위의 함수는 get/post 두가지로 작동하고. 페이지 요청시에는 get.!
# 저장하기 버튼 누르면 post!

pybo/templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->        
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

pybo/templates/pybo/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 네비게이션바 -->
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

</body>
</html>

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="#">로그인</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!--장고에는 템플릿의 특정 위치에 다른 템플릿을 삽입할수 있는 include 태그가 있다. include 
    태그는 보통 템플릿에서 특정 영역이 반복적으로 사용될 경우 중복을 없애 -->

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
    <!-- 오류표시 Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        {% for field in form %}
        {% if field.errors %}
        <div>
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% endif %}
    <!-- 오류표시 End -->
    <div class="mb-3">
        <label for="subject" class="form-label">제목</label>
        <input type="text" class="form-control" name="subject" id="subject"
                value="{{ form.subject.value|default_if_none:'' }}">
    </div>
    <div class="mb-3">
        <label for="content" class="form-label">내용</label>
        <textarea class="form-control" name="content"
                    id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}